### ISSUE TITLE
Data extraction too user unfriendly

### ISSUE THREAD

**Issue by pirate486743186** [Wargus/stratagus#198] opened 2016-11-14 10:29 UTC
It should be stupid proof.
The quirkiness needlessly limits the player pool....

You should do something like openra
There, you extract the data, from within the gui.
one click, and bam.
It put all it needs in a folder in user space.
No need of the command line, or copying manually extra stuff, or sudo, or a weird third parameter or inconsistent behavior between the extraction tools of wartool/startool/war1tool or inconsistent behaviors between wargus/stargus/war1gus.... More complicated installation options, could be changed later with config files, by people that care about it.

Of course, this stays valid for wargus/war1gus too

**Comment by mimooh** [comment] 2016-11-14 11:29
I get the feeling you manually used the tools such as wartool, right? If
I am right then it is likely you followed the instructions at the bottom
of https://github.com/Wargus/wargus "Installation Instructions" which
only proves that we should not advertise this manual on that very page.
If you confirm that this is how you tried to install then I will take
care of improving the instructions.

For the end users this should be more useful:
http://wargus.github.io/

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment] 2016-11-14 11:38
Or you use other linux than ubuntu? We only provide package for
debian/ubuntu :( The installation via stratagus GUI, as you propose, would
resolve the problem with supporting all linux distributions. We still
have that issue with aleona vs warcraft dataset separation unresolved,
so your proposal sounds interesting to me.

-- 
Karol Kreński
tel. 517-302-055

**Comment by timfel** [comment] 2016-11-14 14:34
@pirate486743186 If you use the Windows installer, extraction is part of the install progress. On macOS, you are presented with a dialog that asks you where to find the data on first launch. On debian, data extraction is part of the package install process.

Since the games usually do not ship with graphics (safe for Aleonas Tales), we currently do not have a way to graphically ask the user anything. We would have to pull in some UI framework. I'd rather open a terminal and ship the script that we use as part of the debian package and then ask the user to give the data from where to extract on the terminal. Do you think that would be ok?

**Comment by pirate486743186** [comment] 2016-11-15 00:30
i'm on linux.... but anyway
I run in to some already reported bugs/issues and got really frustrated
I'm changing the direction of the issue....

Look what openra is doing.
(not the download bit XD)
A unified Gui experience across all platforms.

The user should install just "stratagus". In the menu all of the stuff appear right away, maybe all in it's own submenu? If the user clicks on say wargus, a gui appears proposing to extract his data from the CD.... The stuff are extracted in user space. No need for admin rights.
And the whole thing looks the same, no matter where you are.

Yea, an ugly curses menu would do too.
But seriously, have a look at openra.

also, the extractors, should autodetect if it's an unsupported version and report it to the user, instead of just trying and failing and letting the user scratching his head.

**Comment by a-detiste** [comment] 2016-11-15 05:45
Hi,

Having something like it's done for OpenRA would be nice, but _please_ keep the command line tools around; and/or have the command line tools & GUI use some improved shared library.

I still plan someday to bolt something like Lutris on top of Game-Data-Packager to make it the one generic solution for proprietary data needs for free engine.

It now detects Steam, SteamCMD & lGOGdownloader etc...
but I understand that has no use for WarCraft 2 of course.
Now it works on Fedora too, it's already one step further.

Someone else is working on flatpack support, to have it all work without root privilièges.

**Comment by timfel** [comment] 2016-11-18 12:45
As an experiment, I've changed the launchers (on master) to check on startup if the data files exist and are correctly extracted in the correct version. If not, they will ask the user with platform-specific dialogs to point to the location of the data files. The games are now more specific in which data files they ask for:

war1gus asks explicitly for 'data.war';
wargus asks for any of 'rezdat.war', 'Battle.snp' (from the BNE CD), or 'War Resources' (from the Mac CD);
stargus asks for 'stardat.mpq' or 'starcraft.mpq'.

Then the data is automatically extracted to the user directory (under data.GAME_NAME).

For aleonas_tales, we now have a separate launcher that uses the shipped game data.

The extractor tools are still there, of course, they are simply called from the launcher with default arguments.

**Comment by mimooh** [comment] 2016-11-18 15:50
Very interesting!

-- 
Karol Kreński
tel. 517-302-055

**Comment by mimooh** [comment] 2016-11-19 12:54
So is it designed to have stratagus only installation and stratagus is supposed to install game data via some dialogs? Under windows I tried this way but clicking stratagus results in pretty much nothing.

Under linux we now depend on pretty fresh packages, so I need to update the system (ubuntu 2015.04):
The following packages have unmet dependencies:
 stratagus : Depends: libpng16-16 (>= 1.6.2-1) but it is not installable
             Depends: libstdc++6 (>= 5.2) but 4.9.2-10ubuntu13 is to be installed

**Comment by timfel** [comment] 2016-11-19 13:26
New dependencies shouldn't be, the packages are still built on each version of Ubuntu.

And no, the idea is not to install stratagus at all anymore. Just install only Wargus or only War1gus or only Stargus. On Windows and macOS nothing changes here. On Linux, we still have a dependency on stratagus, but the we no longer extract the data as root and into a global directory. Instead we extract the data on first launch into a user folder (like on macOS).

**Comment by mimooh** [comment] 2016-11-19 13:35
I can see there are related commits to wargus repo, so stratagus + wargus must be installed. But how about the idea of just installing stratagus and from within stratagus dialogs launch the procedure:
download wartool/pudconvert/whatever binaries, binaries universal enough to be launched under any (not ancient) linux if that is possible. Place them in some temporary folder. Convert warcraft data to wargus and clean the temporary folder. But perhaps that's a lot of work, so just an idea to consider - could turn out better from what we have now, but what we have now is pretty usable I'd say.

**Comment by mimooh** [comment] 2016-11-19 13:38
@timfel, ok. Started to write my comment before you posted yours.

**Comment by mimooh** [comment] 2016-11-19 13:55
Seems like these dependency problems are not an issue - something's wrong with my system packages.

**Comment by timfel** [comment] 2016-11-19 14:48
@mimooh I don't see how, on Linux, it is really useful to not have to install stratagus+*gus. Putting code to download the games in stratagus just ties these things together (the way it is done in openra encodes in the src of the openra engine the games that are supported. all 3rd party games become second class...)

The engine and the games are separate projects, with the gmaes needing stratagus as a dependency for running. Having the launchers take care of invoking the extractor unifies that experience across all the different games that provide such a launcher (as the *gus games do) by using code in the stratagus repo, so that people don't need to worry about how to prepare the data.

**Comment by mimooh** [comment] 2016-11-19 19:53
I just thought that perhaps deb and rpms could be unified somehow. Just for ubuntu, the way it is installed now is sure fine.

**Comment by mimooh** [comment] 2016-11-23 19:43
Under windows10, wargus.exe from console quitely exists. Aleona starts the game with Aleona dataset. Should I look for presence of some folders somewhere? I am not getting any dialogs about extracting warcraft as I did last week (the new dialog after first launch of wargus I got last week).

**Comment by timfel** [comment] 2016-11-23 20:42
Hm, both shortcuts should work as of Monday... I'll test again on another computer tomorrow

**Comment by timfel** [comment] 2016-11-23 20:44
You can try to delete your User/username/AppData/Roaming/Stratagus/data.Wargus folder.

**Comment by mimooh** [comment] 2016-11-24 17:38
I did deleted this folder, didn't help. I can see warcraft2 data is there in right format under AppData, but is not used. Both aleona and wargus/stratagus.exe launch aleona. I also tried stratagus -d pathToWargus, but aleona started again. Btw, what is the windows way of stratagus -h? I tried stratagus /? and such, but never saw help.

**Comment by timfel** [comment] 2016-11-24 19:05
On Windows, stdout always goes to %APPDATA%\Stratagus\stdout.txt and stderr.txt.

If you launch stratagus -d pathToWargus, you must do it from some folder that does not have aleonas tales in it, because the current working dir takes precendence over the -d argument (yes, that's also not right...)

**Comment by mimooh** [comment] 2016-11-24 21:04
stderr.txt:
Maybe you need to specify another gamepath with '-d /path/to/datadir'?

Even after I copied whole stratagus.exe and dlls to %APPDATA%\Stratagus\data.Wargus and ran  stratagus.exe there.

**Comment by timfel** [comment] 2016-11-24 21:06
Did you check that the scripts directory is populated correctly? It should have a stratagus.lua file, otherwise you'll get that error.

**Comment by mimooh** [comment] 2016-11-24 21:06
perhaps stratagus.exe doesn't accept any parameters? It never complains or returns anything after any switch, stratagus.exe -d /null, stratagus.exe -xyz

**Comment by mimooh** [comment] 2016-11-24 21:09
The problem is indeed under scripts - data.Wargus\scripts\ theres only wc2-config.lua. No complaints about missing scripts

**Comment by timfel** [comment] 2016-11-24 21:17
Did you do a fresh install with a current installer? The windows one only started working on Tuesday... It should be working both from the desktop shortcut and when you start with double click. I haven't checked cmdline launch for Windows at all.

**Comment by mimooh** [comment] 2016-11-24 21:24
I have limited access to windows. Will try tomorrow. Thanks for all the
help!

-- 
Karol Kreński
tel. 517-302-055

**Comment by Kintobor** [comment] 2016-11-24 22:42
Something to remember is that there is a flag in the scripts which identify which data set is being used. You can't run Wargus data when the Aleona flag is set.

**Comment by mimooh** [comment] 2016-11-26 14:47
windows10, uninstalled wargus and installed fresh wargus. Didn't work. So I removed data.Wargus, got the warcraft2 extraction dialog but after all under scripts/ there's just wc2-config.lua, which results in:
Maybe you need to specify another gamepath with '-d /path/to/datadir'?

**Comment by timfel** [comment] 2016-11-26 18:25
Shit, that means the copying mechanism doesn't work. What directory are you
installing to?

mimooh <notifications@github.com> schrieb am Sa., 26. Nov. 2016, 15:47:

**Comment by mimooh** [comment] 2016-11-26 19:22
Everything default. "Program Files x86" and "AppData". Does it only
break at my machine?

-- 
Karol Kreński
tel. 517-302-055

**Comment by timfel** [comment] 2016-11-27 10:33
@mimooh can you try again with the changes I pushed just now?

**Comment by timfel** [comment] 2016-11-27 10:34
you might have to manually delete the %APPDATA%\Stratagus\data.Wargus folder.

**Comment by mimooh** [comment] 2016-11-27 12:32
@timfel, don't have admin priviliges at this very machine, so cannot install. Also, the top of https://github.com/Wargus/stratagus says http://www.stratagus.com/, but should say http://wargus.github.io. Particularly that http://www.stratagus.com says: The web service to this account has been limited temporarily!

@Erenussocrates, are you on windows? Can you install latest wargus from wargus.github.io?

**Comment by mimooh** [comment] 2016-11-27 12:40
Just updated wikipedia that 2.4.1 is the latest. Is is true on wikipedia that all these OSes are supported? Operating system 	AmigaOS 4, BSD, Linux, Mac OS X, MorphOS, AROS, Windows. It also says android is supported but I remember people from war2.ru were asking about it and they were told android is not really supported.

**Comment by Erenussocrates** [comment] 2016-11-27 14:26
@mimooh Yeah, I just tried using the installer and it doesn't work. I'm pretty sure it's wartool's fault, as I've also tried to extract a map using the pudconvert and that also didn't work as well, those extraction programs just seems to be completely unreliable, I wonder why don't they fix it for so long.

**Comment by timfel** [comment] 2016-11-27 18:22
@mimooh didn't you always need admin rights to install?

**Comment by mimooh** [comment] 2016-11-27 18:29
@timfel I was not explicitly asked for the password on my friend's windows machine last couple of weeks, but perhaps I was a priviliged user automatically. Today I tried on a new machine in different place and needed admin access, which I don't have here, so I was not allowed to install.

**Comment by mimooh** [comment] 2016-11-27 18:34
@Erenussocrates come on! The developers are not obligated to do anything. It is supposed to be fun and learning experience for those who choose it.

**Comment by Erenussocrates** [comment] 2016-11-27 19:21
I didn't say they were obligated to lol. But wargus shouldn't be expected to be installed with it's current condition as it is right now, if it can't be installed it's pretty much useless as well.

**Comment by timfel** [comment] 2016-11-27 19:23
@Erenussocrates: so, @mimooh just doesn't have admin. What error do you have? Any dialogs? Any popups?

**Comment by Erenussocrates** [comment] 2016-11-27 19:46
The following command was used to extract the data /C ""D:\testgus\wartool" -v "D:\Warcraft II BNE" "C:\Users\Erenus\AppData\Roaming\Stratagus\data.Wargus""

Wargus data not extracted, is corrupted, or outdated. You need to extract it from original Warcraft II DOS REZDAT.WAR or BNE Battle.snp file.


Those two paragraphs are what I get when I attempt to run the installed game for the first time. (I tried running with Battle.snp) And I attempted to run it in administrator mode as well.

**Comment by mimooh** [comment] 2016-11-28 06:47
The installer works under windows7, thanks a lot timfel :) I tried on yet another windows machine. I will see about the old windows box that caused the problem.

@Erenussocrates, the message that wargus is not extracted or corrupted is supposed to be displayed as part of the installation process. After that you should be getting the dialog to choose the original warcraft2 path. Didn't you get any dialog after the message?

**Comment by timfel** [comment] 2016-11-28 06:50
@Erenussocrates can you open a cmd prompt and run this command and tell me the output:

"D:\testgus\wartool" -v "D:\Warcraft II BNE" "C:\Users\Erenus\AppData\Roaming\Stratagus\data.Wargus"

**Comment by Erenussocrates** [comment] 2016-11-28 13:46
it said it could not find Warcraft 2 data.

**Comment by timfel** [comment] 2016-11-28 14:31
Can you check that your BNE folder includes SUPPORT\TOMES\TOME.1 to TOME.4?

**Comment by Erenussocrates** [comment] 2016-11-28 15:13
there is maindat.war, strdat.war, TOME.2 and TOME.3 . I'm pretty sure those two are already TOME.1 and TOME.4 for BNE though. And they are not in SUPPORT/TOMES, but they are in a folder called "DATA" (I might have created it myself)

**Comment by timfel** [comment] 2016-11-28 15:29
Interesting, I've never seen such a CD. The two BNE versions I have only have the tome files. The DOS versions should all have a data folder with 4 war files: rezdat.war,  maindat.war, strdat.war, and snddat.war

**Comment by timfel** [comment] 2016-11-28 15:34
I will add a facility to check more specifically which kind of data we expect in the extraction tool. There seems to be a range of CDs out there that do not quite fit our expectations, so we need to inform users more clearly and maybe ask for details of the CD folder layout, too.

**Comment by mimooh** [comment] 2016-11-28 19:51
@timfel, I confirm that I get no more issues with the new installer - it works on that windows machine that I had problems with, so thanks once again! I had issues during the installation while the old broken installation was still there - it helped that I removed appdata/roaming/stratagus, but I doubt people will know where wargus now lives on their disk, so I'll add that information to the "it is a bug if you launched the game without arguments (...)" message.

When it comes to the CDs I think I somewhere saw some game identification mechanism based on various original warcrafts2 checksums, but you are probably aware of that.

**Comment by timfel** [comment] 2016-12-12 08:28
One advantage the OpenRA guys have is that the assets for the games have been released publicly, so they can simply offer to download them for you, and they'll never have issues with extraction. Over the weekend I got extraction of the demos for warcraft 1 and 2 to work, so we could offer to automatically download and install those, but that won't really help, since those demos do not even contain all units, so they won't be any good even for just skirmish.

**Comment by mimooh** [comment] 2016-12-12 11:17
I contacted Blizzard last month if they could consider releasing the
assets publicly. Seems like they don't sell Warcraft2 anymore. Still
waiting for reply. Also, I found that there are assets that can be
bought online. They are good quality and not that expensive. Aleona is
not such a good quality in my opinion.

**Comment by CosmeFC** [comment] 2017-05-08 11:35
Are there news from Blizzard?

**Comment by mimooh** [comment] 2017-05-08 11:56
Nope. No answer at all from Blizzard.

**Comment by timfel** [comment] 2018-02-04 14:16
The new extractor has been working for me for Starcraft, Warcraft 1, and Warcraft 2 on Ubuntu, Windows 10, and macOS. I'm closing this in favor of more specific issues

**Closed by timfel** 2018-02-04 14:16 UTC
