### ISSUE TITLE
[macOS] Regression: Black text on main menu in Wargus (Stratagus bug)

### ISSUE THREAD

**Issue by shinra-electric** [Wargus/stratagus#596] opened 2023-12-19 23:04 UTC
This was a tricky one to track down...

When building Wargus recently I noticed the text on the main menu was black. What was odd was that older builds I had archived also had the same issue, whereas they didn't before. However, after a lot of testing I was able to replicate the issue. 

#584 /fix/typos 7b2d62e10098f2f310aca352de84568936a0fafb - OK - White/yellow text
#583 /guichan_official_patched_0_4_0 311a68418cb48e469c84e6fc2065243360150233 - Broken build
#588 /mng a1bd75ec845eb36b6a55dcc2fe1a174a21f1b395 - Broken build
#589 /palette_typo 4c213cc945efc52f4e602f67fa76a09d2f19f839 - Broken build
#592 /guichan_fix fb35843c7e931e96a54798bc08a40277270a684c - Build fix - Black Text

Screenshots: 
#584: 
<img width="1392" alt="Screenshot 2023-12-19 at 23 45 05" src="https://github.com/Wargus/stratagus/assets/50119606/46eee98b-59f1-4a17-af29-6119dba9286c">
#592: 
<img width="1392" alt="Screenshot 2023-12-19 at 23 46 42" src="https://github.com/Wargus/stratagus/assets/50119606/99842f1a-db69-4f81-b875-4c9769692c41">

So the issue that causes the black text is somewhere in between those PRs. 

But the reason why this was confusing to track down was that after I opened a build with the bug, any working builds would also have black text until I deleted the Stratagus source folder. After deleting it, the older working builds reverted to white text. I assume this is related to [this issue](https://github.com/Wargus/wargus/issues/438#issue-1631100130) with wartool, where the rpath is not working.

**Comment by Jarod42** [comment] 2023-12-20 00:23
I updated to last guichan (0.9.0) (with some patches)...
Seems I miss some regressions :-/
Unfortunately, I don't have macOS, and code works locally (on Windows).
I will see if something related to font might be problematic, but unsure to found it :-/

**Comment by YunaBraska** [comment] 2023-12-20 14:08
@Jarod42 I would like to know how I could help, :) How can I help to support macOS again. 
People are starting to play on macOS since Apple Silicon is out.

I have macOS but never worked with C, C++, Lua :( 
On macOS, I can see many further issues.
* Can't save the game because I can't enter the naming field to save the game.
* Translations are there in `po` but I can spot only few translations in the game.
* I can see also many crashes when not playing the campaign. Like generating a random skirmish.
* [...]

**Comment by Jarod42** [comment] 2023-12-23 23:36
guisan (a guichan fork) has similar/worse [issue](https://github.com/kallisti5/guisan/issues/21)...
So I really bet for a bug in guichan between 0.4.0 (2005 may 11th) and guisan fork (2007 dec 22th).

**Comment by zzam** [comment] 2024-02-25 20:38
The same issue happens for me on linux.
I bisected it to:

```
4d7c864520a2185794767f028a92c37c2a3158fc is the first bad commit
commit 4d7c864520a2185794767f028a92c37c2a3158fc
Author: Jarod42 <Jarod42@users.noreply.github.com>
Date:   Sun Nov 19 10:57:14 2023 +0100

    Migrate to latest Guichan.

 src/editor/editloop.cpp |   21 +-
 src/include/font.h      |    2 +-
 src/include/movie.h     |   24 +-
 src/include/video.h     |   26 +-
 src/include/widgets.h   |  205 ++++-----
 src/sound/sound.cpp     |    2 +-
 src/tolua/ui.pkg        |   72 ++--
 src/ui/botpanel.cpp     |    9 +-
 src/ui/mouse.cpp        |   10 +-
 src/ui/widgets.cpp      | 1083 ++++++++++++++++++++---------------------------
 src/video/font.cpp      |   20 +-
 src/video/graphic.cpp   |    1 -
 src/video/mng.cpp       |   20 +-
 src/video/movie.cpp     |   68 +--
 src/video/video.cpp     |    4 +-
 third-party             |    2 +-
 16 files changed, 670 insertions(+), 899 deletions(-)
```

**Comment by Jarod42** [comment] 2024-02-28 14:59
Should be fixed by above PR.

**Closed by Jarod42** 2024-02-28 14:59 UTC

**Comment by shinra-electric** [comment] 2024-02-29 13:32
Yes, I can confirm it's fixed. 

Thanks 👍🏼
