### ISSUE TITLE
Proper translation support

### ISSUE THREAD

**Issue by sheepo99** [Wargus/stratagus#166] opened 2015-12-20 18:09 UTC
I'm not exactly sure where to fit this, since it's more of a request than an issue, so here it goes.

I would like to see more proper support for translation for stratagus and all branch projects (stargus, wargus), namely to have all translation scricpts properly uploaded to a Transifex platform so contributors can join in to translate the project to whatever language of their choice. I would love to see all the fine Blizzard classics finally translated to my own language, since I have experience in translating games in the past.

Furthermore, I'd like to take this opportunity to ask if there is any other way to communicate with the current team? Why is there no official IRC channel for this? It would be of great help for anyone interested and involved in the project to be able to communicate with other members directly.

regards
j

**Comment by timfel** [comment] 2016-02-15 16:12
Hi. Translation support in some ways is already there, although not properly embedded throughout, afaict. The issue is mainly that this is a really, really part time project, so much so that even hanging out on the #stratagus irc channel would be too much commitment for many at this point.

**Comment by Andrettin** [comment] 2016-02-15 16:19
There is translation support in the engine (though as timfel noted some strings still need to be made translatable). The main issue of translating Wargus and etc. though would be a copyright one: to included the texts (translated or otherwise) from WC2 in the Wargus repository would be in breach of Blizzard's copyright .

**Comment by mimooh** [comment] 2016-12-01 22:47
If it's a copyright issue, then none of us can probably solve this. Closing.

**Closed by mimooh** 2016-12-01 22:47 UTC
