### ISSUE TITLE
Compile error. "GL_GLEXT_VERSION" redefined

### ISSUE THREAD

**Issue by ipochto** [Wargus/stratagus#241] opened 2019-02-23 22:14 UTC
Trying to compile on Linux had this issue:

```
Building CXX object CMakeFiles/stratagus.dir/src/action/action_attack.cpp.o
In file included from /home/alyokhin/build/stratagus.aur/src/stratagus/src/include/video.h:46,
                 from /home/alyokhin/build/stratagus.aur/src/stratagus/src/action/action_attack.cpp:60:
/usr/include/SDL/SDL_opengl.h:116: error: "GL_GLEXT_VERSION" redefined [-Werror]
 #define GL_GLEXT_VERSION 29
 
In file included from /usr/include/GL/gl.h:2055,
                 from /usr/include/SDL/SDL_opengl.h:46,
                 from /home/alyokhin/build/stratagus.aur/src/stratagus/src/include/video.h:46,
                 from /home/alyokhin/build/stratagus.aur/src/stratagus/src/action/action_attack.cpp:60:
/usr/include/GL/glext.h:54: note: this is the location of the previous definition
 #define GL_GLEXT_VERSION 20180725
 
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/stratagus.dir/build.make:90: CMakeFiles/stratagus.dir/src/action/action_attack.cpp.o] Error 1
make[2]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/stratagus.dir/all] Error 2
make[1]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
make: *** [Makefile:130: all] Error 2
make: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
==> ERROR: A failure occurred in build().
```

**Comment by ipochto** [comment] 2019-02-24 00:02
A bit more information:
`````
==> Starting build()...
-- Could not find StackTrace
-- Found OggVorbis: /usr/lib/libogg.so;/usr/lib/libvorbis.so
CMake Warning (dev) at /usr/share/cmake-3.13/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:651 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL ES 1.1 libraries: /usr/lib/libSM.so;/usr/lib/libICE.so;/usr/lib/libX11.so;/usr/lib/libXext.so;/usr/lib/libEGL.so;/usr/lib/libGLESv1_CM.so
-- Could not find Native SDL gles
-- Found EGL SDL gles
-- Using OpenGL
==================================
Debug mode: No (Enable by param -DCMAKE_BUILD_TYPE=Debug)
Strip executables: No (Enable by param -DENABLE_STRIP=ON)
Static linking: No (Enable by param -DENABLE_STATIC=ON)
Place game files in: user directory (Place in game directory with -DENABLE_USEGAMEDIR=ON)
Parallel building in MSVC: Yes (Disable by param -DENABLE_MULTIBUILD=OFF)
Platform: Linux
Redirect stdio: Unsupported on this platform
Touchscreen input: No (Enable by param -DENABLE_TOUCHSCREEN=ON)
Doxygen documentation: No (Enable by param -DENABLE_DOC=ON)
Game development files: No (Enable by param -DENABLE_DEV=ON)
Upx packer: No (Enable by param -DENABLE_UPX=ON)
NSIS Installer: Unsupported on this platform
Bzip2: Found and enabled (Disable by param -DWITH_BZIP2=OFF)
FluidSynth: Found and enabled (Disable by param -DWITH_FLUIDSYNTH=OFF)
MikMod: Found and enabled (Disable by param -DWITH_MIKMOD=OFF)
Mng: Found and enabled (Disable by param -DWITH_MNG=OFF)
Ogg/Vorbis: Found and enabled (Disable by param -DWITH_OGGVORBIS=OFF)
StackTrace: Not Found
Theora: Found and enabled (Disable by param -DWITH_THEORA=OFF)
X11: Found and enabled (Disable by param -DWITH_X11=OFF)
Renderer: OpenGL (Disable by param -DWITH_RENDERER=NativeSDL)
==================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/alyokhin/build/stratagus.aur/src/build
make: Entering directory '/home/alyokhin/build/stratagus.aur/src/build'
make[1]: Entering directory '/home/alyokhin/build/stratagus.aur/src/build'
make[2]: Entering directory '/home/alyokhin/build/stratagus.aur/src/build'
make[2]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
[  0%] Built target genversion
make[2]: Entering directory '/home/alyokhin/build/stratagus.aur/src/build'
make[2]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
[  3%] Built target metaserver
make[2]: Entering directory '/home/alyokhin/build/stratagus.aur/src/build'
Scanning dependencies of target stratagus
make[2]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
make[2]: Entering directory '/home/alyokhin/build/stratagus.aur/src/build'
[  3%] Building CXX object CMakeFiles/stratagus.dir/src/action/action_attack.cpp.o
In file included from /home/alyokhin/build/stratagus.aur/src/stratagus/src/include/video.h:46,
                 from /home/alyokhin/build/stratagus.aur/src/stratagus/src/action/action_attack.cpp:60:
/usr/include/SDL/SDL_opengl.h:116: error: "GL_GLEXT_VERSION" redefined [-Werror]
 #define GL_GLEXT_VERSION 29
 
In file included from /usr/include/GL/gl.h:2055,
                 from /usr/include/SDL/SDL_opengl.h:46,
                 from /home/alyokhin/build/stratagus.aur/src/stratagus/src/include/video.h:46,
                 from /home/alyokhin/build/stratagus.aur/src/stratagus/src/action/action_attack.cpp:60:
/usr/include/GL/glext.h:54: note: this is the location of the previous definition
 #define GL_GLEXT_VERSION 20180725
 
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/stratagus.dir/build.make:90: CMakeFiles/stratagus.dir/src/action/action_attack.cpp.o] Error 1
make[2]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/stratagus.dir/all] Error 2
make[1]: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
make: *** [Makefile:130: all] Error 2
make: Leaving directory '/home/alyokhin/build/stratagus.aur/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by mnhauke** [comment] 2019-03-03 21:56
The cause is that SDL contains a copy of glext.h because some systems are delivered without it. The bundled copy then conflicts with a version provided by you system (Mesa).

The solution is to unbundle glext.h from SDL and only use the one provided by your system.

See https://bugzilla.redhat.com/show_bug.cgi?id=1662778 for more information
Patch for SDL: https://src.fedoraproject.org/rpms/SDL/raw/master/f/SDL-1.2.15-Use-system-glext.h.patch


 
--

**Comment by ipochto** [comment] 2019-03-04 08:01
Thank you!

**Comment by timfel** [comment] 2019-04-06 15:20
I've applied a fix for this to master

**Closed by timfel** 2019-04-06 15:20 UTC
